import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import Link from "next/link";
import Slider from "./components/Slider";
import Cookies from "js-cookie";
import { authMiddleware } from "./middleware/authMiddleware";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // Cookies.remove("jwtToken");
  // Cookies.set("jwtToken", jwtToken, { expires: 7 });
  // Cookies.get("name"); // => 'value'
  const auth = authMiddleware();
  const isAuth = auth.isAuthenticated;

  console.log("is AUth from home page", isAuth);

  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home-div">
        <div className="bg-dark text-white text-center home-banner-div">
          <div className="blog-tag">
            <p className="blog-tag-p mb-5">Write creative blogs</p>
            {isAuth ? (
              <Link href="/dashboard/addBlog" className="home-page-btn">
                CREATE YOUR BLOG
              </Link>
            ) : (
              <Link href="/signin" className="home-page-btn">
                CREATE YOUR BLOG
              </Link>
            )}

            {/* <button className="home-page-btn"></button> */}
          </div>
        </div>
        <div className="blog-slider mt-1">
          <Slider title="Popular Blogs" />
        </div>
      </div>
    </>
  );
}
